window.DEFAULT_CONFIG = {
  "assignedFamilies": {
    "Flautín": "Maderas de timbre \"redondo\"",
    "Flauta 1": "Maderas de timbre \"redondo\"",
    "Flauta 2": "Maderas de timbre \"redondo\"",
    "Clarinete (Si Bemol) I": "Maderas de timbre \"redondo\"",
    "Clarinete (Si Bemol) II": "Maderas de timbre \"redondo\"",
    "Clarinete (Si Bemol) III": "Maderas de timbre \"redondo\"",
    "Clarinete bajo": "Maderas de timbre \"redondo\"",
    "Oboe 1": "Dobles cañas",
    "Oboe 2": "Dobles cañas",
    "Fagot 1": "Dobles cañas",
    "Fagot 2": "Dobles cañas",
    "Saxofón soprano": "Saxofones",
    "Saxofón alto": "Saxofones",
    "Saxofón tenor": "Saxofones",
    "Saxofón barítono": "Saxofones",
    "Corno francés (Sol) 1": "Cornos",
    "Corno francés (Sol) 2": "Cornos",
    "Corno francés (Sol) 3": "Cornos",
    "Corno francés (Sol) 4": "Cornos",
    "Trompeta (Si Bemol) 1": "Metales",
    "Trompeta (Si Bemol) 2": "Metales",
    "Trompeta (Si Bemol) 3": "Metales",
    "Trompeta (Si Bemol) 4": "Metales",
    "Trombón 1": "Metales",
    "Trombón 2": "Metales",
    "Trombón 3": "Metales",
    "Trombón 4": "Metales",
    "Bombardino (Si Bemol) 1": "Metales",
    "Bombardino (Si Bemol) 2": "Metales",
    "Tuba": "Metales",
    "Percusión": "Percusión menor",
    "Claves": "Percusión menor",
    "Timbal de concierto": "Tambores",
    "Conga": "Tambores",
    "Platillo de orquesta": "Platillos",
    "Piano": "Auxiliares",
    "Contrabajo": "Cuerdas frotadas",
    "Violín": "Cuerdas frotadas",
    "Track 0": "Auxiliares",
    "Flaut�n": "Maderas de timbre \"redondo\"",
    "Saxof�n soprano": "Saxofones",
    "Saxof�n alto": "Saxofones",
    "Saxof�n tenor": "Saxofones",
    "Saxof�n bar�tono": "Saxofones",
    "Tromb�n 1": "Metales",
    "Tromb�n 2": "Metales",
    "Tromb�n 3": "Metales",
    "Tromb�n 4": "Metales",
    "Corno franc�s (Sol) 1": "Cornos",
    "Corno franc�s (Sol) 2": "Cornos",
    "Corno franc�s (Sol) 3": "Cornos",
    "Corno franc�s (Sol) 4": "Cornos",
    "Percusi�n": "Percusión menor",
    "Viol�n": "Custom 1"
  },
  "familyCustomizations": {
    "Metales": {
      "color": "#edd113",
      "shape": "roundedSquare",
      "secondaryColor": "#FFFFFF"
    },
    "Cornos": {
      "color": "#edbe13",
      "shape": "roundedSquareDouble",
      "secondaryColor": "#FFFFFF"
    },
    "Maderas de timbre \"redondo\"": {
      "color": "#769df3",
      "shape": "roundedSquare",
      "secondaryColor": "#FFFFFF"
    },
    "Dobles cañas": {
      "color": "#c23afd",
      "shape": "sixPointStar",
      "secondaryColor": "#FFFFFF"
    },
    "Saxofones": {
      "color": "#ce8767",
      "shape": "fourPointStar",
      "secondaryColor": "#FFFFFF"
    },
    "Placas": {
      "color": "#ff0000",
      "shape": "diamondDouble",
      "secondaryColor": "#FFFFFF"
    },
    "Auxiliares": {
      "color": "#347875",
      "shape": "roundedSquareDouble",
      "secondaryColor": "#FFFFFF"
    },
    "Cuerdas frotadas": {
      "color": "#41e342",
      "shape": "diamond",
      "secondaryColor": "#FFFFFF"
    },
    "Cuerdas pulsadas": {
      "color": "#1abeb4",
      "shape": "triangle",
      "secondaryColor": "#FFFFFF"
    },
    "Voces": {
      "color": "#bebebe",
      "shape": "squareDouble",
      "secondaryColor": "#FFFFFF"
    },
    "Custom 1": {
      "color": "#d52b2b",
      "shape": "diamond",
      "secondaryColor": "#FFFFFF"
    },
    "Percusión menor": {
      "color": "#a78269",
      "shape": "square",
      "secondaryColor": "#FFFFFF"
    }
  },
  "enabledInstruments": {
    "Track 0": true,
    "Flautn": true,
    "Flauta 1": true,
    "Flauta 2": true,
    "Oboe 1": true,
    "Oboe 2": true,
    "Clarinete (Si Bemol) I": true,
    "Clarinete (Si Bemol) II": true,
    "Clarinete (Si Bemol) III": true,
    "Clarinete bajo": true,
    "Fagot 1": true,
    "Fagot 2": true,
    "Saxofn soprano": true,
    "Saxofn alto": true,
    "Saxofn tenor": true,
    "Saxofn bartono": true,
    "Corno francs (Sol) 1": true,
    "Corno francs (Sol) 2": true,
    "Corno francs (Sol) 3": true,
    "Corno francs (Sol) 4": true,
    "Trompeta (Si Bemol) 1": true,
    "Trompeta (Si Bemol) 2": true,
    "Trompeta (Si Bemol) 3": true,
    "Trompeta (Si Bemol) 4": true,
    "Trombn 1": true,
    "Trombn 2": true,
    "Trombn 3": true,
    "Trombn 4": true,
    "Bombardino (Si Bemol) 1": true,
    "Bombardino (Si Bemol) 2": true,
    "Tuba": true,
    "Contrabajo": true,
    "Timbal de concierto": false,
    "Platillo de orquesta": false,
    "Percusin": false,
    "Conga": false,
    "Claves": true,
    "Violn": true,
    "Piano": false,
    "Flautn": true,
    "Saxofn soprano": true,
    "Saxofn alto": true,
    "Saxofn tenor": true,
    "Saxofn bartono": true,
    "Corno francs (Sol) 1": true,
    "Corno francs (Sol) 2": true,
    "Corno francs (Sol) 3": true,
    "Corno francs (Sol) 4": true,
    "Trombn 1": true,
    "Trombn 2": true,
    "Trombn 3": true,
    "Trombn 4": true,
    "Percusin": true,
    "Violn": true,
    "Flautín": true,
    "Saxofón soprano": true,
    "Saxofón alto": true,
    "Saxofón tenor": true,
    "Saxofón barítono": true,
    "Corno francés (Sol) 1": true,
    "Corno francés (Sol) 2": true,
    "Corno francés (Sol) 3": true,
    "Corno francés (Sol) 4": true,
    "Trombón 1": true,
    "Trombón 2": true,
    "Trombón 3": true,
    "Trombón 4": true,
    "Percusión": false,
    "Violín": true,
    "Flauta": true,
    "Oboe": true,
    "Clarinete": true,
    "Fagot": true,
    "Trompeta": true,
    "Flaut�n": true,
    "Saxof�n soprano": true,
    "Saxof�n alto": true,
    "Saxof�n tenor": true,
    "Saxof�n bar�tono": true,
    "Corno franc�s (Sol) 1": true,
    "Corno franc�s (Sol) 2": true,
    "Corno franc�s (Sol) 3": true,
    "Corno franc�s (Sol) 4": true,
    "Tromb�n 1": true,
    "Tromb�n 2": true,
    "Tromb�n 3": true,
    "Tromb�n 4": true,
    "Percusi�n": false,
    "Viol�n": true,
    "P1": true,
    "P2": true,
    "P3": true,
    "P4": true,
    "P5": true,
    "P6": true,
    "P7": true,
    "P8": true,
    "P9": true,
    "P10": true,
    "P11": true,
    "P12": true,
    "P13": true,
    "P14": true,
    "P15": true,
    "P16": true,
    "P17": true,
    "P18": true,
    "P19": true,
    "P20": true,
    "P21": true,
    "P22": true,
    "P23": true,
    "P24": true,
    "P25": true,
    "P26": true,
    "P27": true,
    "P28": true,
    "P29": true,
    "P30": true,
    "P31": true,
    "P32": true,
    "P33": true,
    "P34": true,
    "P35": true,
    "P36": true,
    "P37": true,
    "P38": true,
    "Clarinete 1": true,
    "Clarinete 2": true,
    "Clarinete 3": true,
    "Saxofon soprano": true,
    "Saxofon alto": true,
    "Saxofon tenor": true,
    "Saxofon": true,
    "Corno frances 1": true,
    "Corno frances 2": true,
    "Corno frances 3": true,
    "Corno frances 4": true,
    "Trompeta 1": true,
    "Trompeta 2": true,
    "Trompeta 3": true,
    "Trompeta 4": true,
    "Trombon 1": true,
    "Trombon 2": true,
    "Trombon 3": true,
    "Trombon 4": true,
    "Bombardino 1": true,
    "Bombardino 2": true,
    "Timbal": true,
    "Percusion": true,
    "Violin": true
  },
  "velocityBase": 67,
  "opacityScale": {
    "edge": 0,
    "mid": 1
  },
  "glowStrength": 0.1,
  "bumpControl": 1.1,
  "visibleSeconds": 8,
  "heightScale": {
    "global": 1.8,
    "families": {}
  },
  "shapeExtensions": {
    "circle": true,
    "circleDouble": true,
    "square": true,
    "squareDouble": true,
    "roundedSquare": true,
    "roundedSquareDouble": true,
    "diamond": true,
    "diamondDouble": true,
    "hexagon": true,
    "hexagonDouble": true,
    "fourPointStar": true,
    "fourPointStarDouble": true,
    "sixPointStar": true,
    "sixPointStarDouble": true,
    "triangle": true,
    "triangleDouble": true
  }
};
